### ISSUE TITLE
Upgrade to sbt 1.0.1

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/iota#67]
We should upgrade to `sbt-freestyle` **0.2.1** (`addSbtPlugin("io.frees" % "sbt-freestyle" % "0.2.1")`) and ports `iota` to sbt **1.0.1**.

There is a WIP https://github.com/frees-io/iota/tree/port-to-sbt-1.0.x, blocked because `AutoTLSPlugin` it's tied to sbt 0.13.

**Comment by suhasgaddam** [comment]
@juanpedromoreno 
https://github.com/frees-io/iota/tree/sg-port-to-sbt-1.0.x should be finished. Feel free to push/trash/cherry-pick the branch.

```scala
  def overrideSwitchCommand: Command =
    Command.arb(Cross.requireSession(Cross.switchParser), CommandStrings.switchHelp)(switchCommandImpl)		
```
This snippet was using a lot of now private methods in sbt 1.0.

So I ended up copy pasting most of the required snippets into:
https://github.com/frees-io/iota/compare/sg-port-to-sbt-1.0.x#diff-c3b7f539f0c1b9fcb3c518e0704ae7eb

Is there a better way? If not, there needs to be appropriate license headers and attribution for that file. As far I can tell, they are compatible(BSD/ASLv2)... There are a few methods that were written under ASLv2(before the copy/paste).
https://github.com/sbt/sbt/blob/v1.0.1/main/src/main/scala/sbt/Cross.scala

I removed `fork in run := true`, because `bench/compile` code generation didn't seem to be closing a file handle when forked.

`iota` has a dependency on cats 1.0.

Comparisons:
https://github.com/frees-io/iota/compare/master...sg-port-to-sbt-1.0.x
https://github.com/frees-io/iota/compare/port-to-sbt-1.0.x...sg-port-to-sbt-1.0.x
